language: python
sudo: required
services:
- docker
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install mypy
- pip install .
script:
- mypy src --ignore-missing-imports
notifications:
  email: false
deploy:
  - provider: pypi
    user: ChrisTimperley
    on:
      tags: true
      python: 3.5
    password:
      secure: LB8oRJCnvgIZX79RSkuniSBK1JOh5MO9W4UUolrAEUmbu/JLyC5eZz53EDRwEgGtS+ssJ+Q6QbbnrAP3pblelcaI00L2wo9AzCnCm4/HtGSCclG0YexwKnUlBo6WiIcD6CxgfwtwbQKjS3B211KXIC76z/fdh81S6URD4DKJ4pLFAXkAv2P3+7KTMLLWaI3orM8NZnkW5/Xq3acZtyhW5VBOmGS8SocqrqpDup19UEzvb64kIOlXs7oA9lOMeDwNX/07A37GFNIUmYokA+N+00cRFnKddKK17dnA8m/2usDO3wET3TTsU4g+uRjaPQFI1vvYu35x7IlLjB1cwwS7s8KF/IEHWy4+b2HWXbCahEOtl4/32Qdte4dNc2g6+6Gy4fzWXF3wadee85T8MlShiIBmy0uwPJAz363f/TYCYFQSFi2jOYzt0XseO8kfIKZkOgrQyiwG/inxfgfXuHZScyPzdEiz4PBSFru5LUiDxKt8jROMpR/tIAJ3NDCw8Z+4+9jQfntku+ltqQsypS8UXO2fZCxQgz+J/o8L+pE3+WW1UHybbNptPKr0QvmPzE8QpYBQ4hyPaaWSl5sEhswn+3EtwPyzJKphqLgsQN8PXcGvB/XTGGy6gg5ljgBvT932VBOuVDEICZJg1MKhrPp8Gcz4ivMxu32L96ayEk/jIMA=
